#!/usr/bin/env node
/**
 * Generates src/theme/theme.css from src/theme/tokens.mjs.
 *
 * How a theme is chosen, with no JavaScript on the initial load:
 *
 *   <html>                  light — the default, from :root alone
 *   <html class="theme-light">   light, even if the system is dark
 *   <html class="theme-dark">    dark
 *   <html class="theme-auto">    follows the operating system, through a
 *                                prefers-color-scheme media query
 *   <html class="theme-<name>">  any further theme added to THEMES
 *
 * The class is the whole switch. A visitor's saved choice reaches the first
 * paint because the Worker reads the `fmt-theme` cookie and writes the class
 * onto <html> before the page is sent (worker/index.ts), so there is no flash
 * of the wrong theme and no inline script in the head.
 *
 * Each semantic token becomes a raw custom property (--fmt-canvas) that the
 * theme classes set, and a Tailwind color (--color-canvas) that points at it.
 * The bridge is `@theme inline`, so a utility like bg-canvas compiles to
 * var(--fmt-canvas) and follows the class at runtime rather than freezing the
 * light value in at build time.
 */
import { writeFileSync } from 'node:fs';
import { DEFAULT_THEME, THEMES } from '../src/theme/tokens.mjs';

const OUT = 'src/theme/theme.css';

const decls = (theme, indent) =>
  [`${indent}color-scheme: ${theme.scheme};`,
    ...Object.entries(theme.tokens).map(([k, v]) => `${indent}--fmt-${k}: ${v};`)].join('\n');

const base = THEMES[DEFAULT_THEME];
const others = Object.entries(THEMES).filter(([name]) => name !== DEFAULT_THEME);
const dark = THEMES.dark;

const css = [
  '/* GENERATED by scripts/build-theme.mjs from src/theme/tokens.mjs.',
  ' * Edit the tokens, then run: node scripts/build-theme.mjs */',
  '',
  `/* ${DEFAULT_THEME[0].toUpperCase() + DEFAULT_THEME.slice(1)}: the default. No class and no JavaScript gives this. */`,
  `:root,`,
  `:root.theme-${DEFAULT_THEME} {`,
  decls(base, '  '),
  '}',
  '',
  ...others.flatMap(([name, theme]) => [
    `:root.theme-${name} {`,
    decls(theme, '  '),
    '}',
    '',
  ]),
  ...(dark
    ? [
        '/* theme-auto follows the operating system, still without JavaScript. */',
        '@media (prefers-color-scheme: dark) {',
        '  :root.theme-auto {',
        decls(dark, '    '),
        '  }',
        '}',
        '',
      ]
    : []),
  '/* Tailwind utilities for every token: bg-canvas, text-fg, border-line … */',
  '@theme inline {',
  ...Object.keys(base.tokens).map((k) => `  --color-${k}: var(--fmt-${k});`),
  '}',
  '',
].join('\n');

writeFileSync(OUT, css);
console.log(`Wrote ${OUT}: ${Object.keys(THEMES).length} themes, ${Object.keys(base.tokens).length} tokens.`);
